config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: { sessions: "usuarios/sessions" }, path_prefix: "auth"

  resources :home
  resources :informacion_general
  resources :graficos

  resources :pagares do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
    get :pagare_odt, on: :collection, defaults: { :format => "odt" }
    get :calendario_pdf, on: :collection, defaults: { :format => "pdf" }
  end

  resources :comprobantes do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
    get :obtener_pagare_socios, on: :collection
    get :obtener_informacion_cuotas, on: :collection
    get :obtener_totales, on: :collection
    get :comprobante_odt, on: :collection, defaults: { :format => "odt" }
  end

  resources :socios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :cargos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :roles do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :tasa_cambios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end
  match 'tasa_cambios/bcn_webservice' => 'tasa_cambios#bcn_webservice', via: :post

  resources :empresa

  resources :bancos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :exceden_prestamos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :clientes_nuevos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :clientes_cuotas_vencidas do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :clientes_morosos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :formas_pagos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :valor_leches do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :usuarios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  match 'tasa_cambio_leche' => 'valor_leches#crear_tasa_cambio_diaria', via: :post
  match 'obtener_pagare_socios' => 'comprobantes#obtener_pagare_socios', via: :get
  match 'obtener_informacion_cuotas' => 'comprobantes#obtener_informacion_cuotas', via: :get
  match 'obtener_totales' => 'comprobantes#obtener_totales', via: :get
  root to: "home#index"
end

app/models/cargo.rb
class Cargo < ApplicationRecord
    validates :nombre, presence: true
    validates :descripcion, presence: true
    validates_length_of :nombre, minimum: 1, maximum: 255

    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "descripcion", "id", "nombre", "updated_at"]
    end
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  include Controleable
  before_action :authenticate_usuario!
  before_action :coleccion_inicial, only: %i[index excel_index]

  def coleccion_inicial
    params[:q] ||= {}
    @coleccion = Cargo.ransack(params[:q])
    respond_to do |formato|
      formato.html do
        @registros = @coleccion.result.page(params[:page])
      end
      formato.xlsx do
        @registros = @coleccion.result
      end
    end
  end

  def index
    authorize!(:read, :Cargos)
    @params_permit = params[:q].present? ? {q: params[:q] .permit! } : {}
    render template: "cargos/index",  layout: "layouts/application"
  end

  def new
    authorize!(:create, :Cargos)
    render template: "cargos/form", layout: "layouts/application"
  end

  def show
    authorize!(:update, :Cargos)
    render template: "cargos/form", layout: "layouts/application"
  end

  def edit
    authorize!(:update, :Cargos)
    render template: "cargos/form", layout: "layouts/application"
  end

  def excel_index
    respond_to do |formato|
      formato.xlsx do
        render(
          xlsx: "excel_index",
          filename: "Cargos del sistema - #{Date.today}.xlsx"
        )
      end
    end
  end

  def create
    begin
      if @registro.save!
        flash[:notice] = "El registro fue guardado exitosamente"
        redirect_to action: :index
      end
    rescue StandardError => e
      flash[:error] = "Ocurrio un error al guardar los datos" if flash.now[:error].blank?
      render template: "cargos/form", layout: "layouts/application"
    end
  end

  def update
    begin
      if @registro.save!
        flash[:notice] = "El registro fue actualizado exitosamente"
        redirect_to action: :index
      end
    rescue StandardError => e
      flash[:error] = "Ocurrio un error al actualizar los datos" if flash.now[:error].blank?
      render template: "cargos/form", layout: "layouts/application"
    end
  end

  def destroy
    authorize!(:destroy, :Cargos)
    begin
      flash[:notice] = "El registro ha sido eliminado exitosamente" if @registro.destroy
    rescue StandardError => e
      flash[:error] = e.message
    end

    redirect_to action: :index, search: params[:q]
  end

  private

    def nombre_recurso
      "Cargo"
    end

    def cargos_params
      params.require(:cargos).permit(:id, :nombre, :descripcion)
    end

    alias :params_permit :cargos_params
end

app/views/cargos/_cargos_formulario.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="card-wrapper">
            <div class="card">
                <div class="card-header">
                    <h3 class="mb-0">Información del Cargo</h3>
                </div>
                <div class="card-body">
                    <%= hidden_field(:cargos, :id, :value => @registro.id) %>
                    <div class="form-group">
                        <label class="form-control-label" for="nombre">Nombre</label>
                        <%= text_field(:cargos, :nombre, class: "form-control", id: "nombre", value: @registro.nombre) %>
                        <p class="text-danger"><%= @registro.errors[:nombre].first %></p>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="nombre">Descripción</label>
                        <%= text_field(:cargos, :descripcion, class: "form-control", id: "descripcion", value: @registro.descripcion) %>
                        <p class="text-danger"><%= @registro.errors[:descripcion].first %></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/cargos/_filtros.html.erb
<div class="col-lg-6 text-left">
    <button class="btn btn-lg btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="btn-inner--icon"><i class="fas fa-search"></i></span>
            <span class="btn-inner--text">Filtros</span>
    </button>

    <div class="dropdown-menu w-60">
        <%= search_form_for @coleccion, url: cargos_path, class: "px-4 py-3 text-center" do |formulario| %>
            <div class="form-group text-left">
                <%= label_tag(:nombre_cont, "Nombre:") %>
                <%= text_field_tag "q[nombre_cont]", params[:q][:nombre_cont], class: "form-control" %>
            </div>
            <%= formulario.submit class: "btn btn-primary text-center" %>
            <%= link_to "Quitar Filtros", cargos_path, class: "btn btn-danger text-center" %>
        <% end %>
     </div>
</div>

app/views/cargos/form.html.erb
<% content_for :titulo_seccion do %>
  Cargos
<% end %>

<%= render "shared/flash", flash: flash %>
<%= render partial: 'cargos/cargos_formulario', layout: "layouts/formulario",
    locals: {
        registro: @registro,
        url: @url
    }
%>

app/views/cargos/index.html.erb
<% content_for :titulo_seccion do %>
  Cargos
<% end %>

<div class="col-lg-12 col-12">
   <div class="row">
      <%= render 'cargos/filtros' %>
      <div class="col-lg-6 text-right">
         <%= link_to "Descargar Excel", excel_index_cargos_path(@params_permit), class: "btn btn-lg btn-success" %>
         <%= link_to "Crear Recurso", new_cargo_path, class: "btn btn-lg btn-neutral" %>
      </div>
   </div>
</div>

<div class="container-fluid mt-3">
   <div class="row">
      <div class="col pl-0 pr-0">
         <div class="card">
            <div class="card-header">
               <h3 class="mb-0">Cargos registrados</h3>
            </div>
            <div class="table-responsive">
               <table class="table align-items-center table-flush">
                  <thead class="thead-light">
                     <tr>
                        <th class="sort"><%= sort_link(@coleccion, :id, "ID") %></th>
                        <th class="sort"><%= sort_link(@coleccion, :nombre, "Nombre") %></th>
                        <th>Descripción</th>
                        <th>Actualizar</th>
                        <th>Eliminar</th>
                     </tr>
                  </thead>
                  <tbody class="list">
                    <% @registros.each do |cargo| %>
                     <tr>
                        <td><%= cargo.id %></td>
                        <td><%= cargo.nombre %></td>
                        <td><%= cargo.descripcion %></td>
                        <td>
                           <%= link_to edit_cargo_path(cargo), class: "btn btn-icon btn-primary" do %>
                              <i class="ni ni-align-left-2"></i>
                           <% end %>
                        </td>
                        <td>
                           <%= link_to cargo_path(cargo), class: "btn btn-icon btn-danger", method: :delete do %>
                              <i class="ni ni-scissors"></i>
                           <% end %>
                        </td>
                     </tr>
                    <% end %>
                  </tbody>
               </table>
            </div>
            <div class="card-footer py-4">
             <%= paginate @registros %>
             <%= page_entries_info @registros %>
            </div>
         </div>
      </div>
   </div>
</div>