config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: { sessions: "usuarios/sessions" }, path_prefix: "auth"

  resources :home
  resources :informacion_general
  resources :graficos

  resources :pagares do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
    get :pagare_odt, on: :collection, defaults: { :format => "odt" }
    get :calendario_pdf, on: :collection, defaults: { :format => "pdf" }
  end

  resources :comprobantes do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
    get :obtener_pagare_socios, on: :collection
    get :obtener_informacion_cuotas, on: :collection
    get :obtener_totales, on: :collection
    get :comprobante_odt, on: :collection, defaults: { :format => "odt" }
  end

  resources :socios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :cargos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :roles do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :tasa_cambios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end
  match 'tasa_cambios/bcn_webservice' => 'tasa_cambios#bcn_webservice', via: :post

  resources :empresa

  resources :bancos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :exceden_prestamos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :clientes_nuevos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :clientes_cuotas_vencidas do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :clientes_morosos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :formas_pagos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :valor_leches do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :usuarios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  match 'tasa_cambio_leche' => 'valor_leches#crear_tasa_cambio_diaria', via: :post
  match 'obtener_pagare_socios' => 'comprobantes#obtener_pagare_socios', via: :get
  match 'obtener_informacion_cuotas' => 'comprobantes#obtener_informacion_cuotas', via: :get
  match 'obtener_totales' => 'comprobantes#obtener_totales', via: :get
  root to: "home#index"
end

app/models/comprobante.rb
class Comprobante < ApplicationRecord
    SALDO_CERO = 0
    belongs_to :socio
    belongs_to :pagare
    belongs_to :usuario
    validate :validar_monto_pagado
    after_create_commit  :crear_pago_pagare
    validate :validar_pago_mora
    before_destroy :validar_ultima_cuota
    before_destroy :revertir_cuotas

    has_many :comprobante_detalle, dependent: :destroy, inverse_of: :comprobante
    accepts_nested_attributes_for :comprobante_detalle, allow_destroy: true

    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "id", "monto_pagado", "numero_comprobante", "observacion", "pagare_id", "socio_id", "tipo_moneda_id", "updated_at", "usuario_id"]
    end


    def obtener_numero
        (numero_comprobante.nil?) ? Comprobante.count + 1 : numero_comprobante
    end

    def validar_monto_pagado
        monto_total = pagare.cuotas.sum(&:monto_con_mora) - pagare.cuotas.sum(&:monto_abonado)
        errors.add(:pagare_id, "El monto pagado sobrepasa el restante del pagare") if monto_total < monto_pagado
    end

    def validar_pago_mora
        proxima_cuota = Cuota.where(pagare_id: pagare_id, cancelado: false).order("fecha_pago asc").first
        return if proxima_cuota.calcular_mora == SALDO_CERO
        errors.add(:pagare_id, "La cuota tiene mora, es necesario pagarla en su totalidad") if proxima_cuota.monto_con_mora != monto_pagado
    end

    def crear_pago_pagare
        cuotas_pendientes = Cuota.where(pagare_id: pagare_id, cancelado: false).order("fecha_pago asc")
        cuota_proxima_pagar = cuotas_pendientes.first
        monto_cuota_pagar = cuota_proxima_pagar.monto_con_mora - cuota_proxima_pagar.monto_abonado
        monto_pagado_socio = monto_pagado

        if monto_cuota_pagar >= monto_pagado_socio
            monto_con_mora = cuota_proxima_pagar.monto_con_mora
            mora_cuota = cuota_proxima_pagar.calcular_mora
            cuota_proxima_pagar.monto_abonado += monto_pagado_socio
            cuota_proxima_pagar.cancelado = true if cuota_proxima_pagar.monto_abonado == monto_con_mora
            cuota_proxima_pagar.mora = mora_cuota if cuota_proxima_pagar.cancelado
            cuota_proxima_pagar.save!
        else
            cuotas_pendientes.each do |cuota|
                break if monto_pagado_socio <= SALDO_CERO
                monto_cuota_pagar = cuota.cuota - cuota.monto_abonado

                cuota.monto_abonado += if monto_cuota_pagar >= monto_pagado_socio
                    monto_pagado_socio
                else
                    monto_cuota_pagar
                end

                cuota.cancelado = true if cuota.monto_abonado == cuota.cuota
                cuota.mora = SALDO_CERO
                cuota.save!
                monto_pagado_socio -= monto_cuota_pagar
            end
        end
    end

    def validar_ultima_cuota
        comprobante = Comprobante.where(pagare_id: pagare_id).order("created_at desc").first
        raise StandardError.new "No se puede eliminar el comprobante, no es el ultimo creado" if comprobante != self
    end

    def revertir_cuotas
        cuotas_pagadas = Cuota.where(pagare_id: pagare_id, cancelado: true).order("fecha_pago desc")
        monto_pagado_socio = monto_pagado

        cuotas_pagadas.each do |cuota|
            break if monto_pagado_socio <= SALDO_CERO
            monto_cuota = cuota.monto_abonado
            monto_abonado = cuota.monto_abonado - monto_pagado

            cuota.monto_abonado = if monto_abonado > 0
                monto_abonado
            else
                SALDO_CERO
            end

            cuota.mora = nil
            cuota.cancelado = false
            cuota.save!
            monto_pagado_socio -= if monto_abonado > 0
                monto_abonado
            else
                monto_cuota
            end
        end
    end
end

app/controllers/comprobante_controller.rb
class ComprobanteController < ApplicationController
  before_action :authenticate_usuario!
  load_and_authorize_resource class: :Comprobante

  def index
    render template: "comprobante/index",  layout: 'layouts/application'
  end

  def show
  end

  def new
    render template: "comprobante/form",  layout: 'layouts/application'
  end
end

app/controllers/comprobantes_controller.rb
class ComprobantesController < ApplicationController
    include Controleable
    before_action :authenticate_usuario!
    before_action :configurar_comprobante, only: %i[create]
    before_action :coleccion_inicial, only: %i[index excel_index]

    def coleccion_inicial
      params[:q] ||= {}
      @coleccion = Comprobante.ransack(params[:q])
      respond_to do |formato|
        formato.html do
          @registros = @coleccion.result.page(params[:page])
        end
        formato.xlsx do
          @registros = @coleccion.result
        end
      end
    end

    def index
      authorize!(:read, :Comprobante)
      @params_permit = params[:q].present? ? {q: params[:q] .permit! } : {}
      render template: "comprobantes/index",  layout: "layouts/application"
    end

    def new
      authorize!(:create, :Comprobante)
      render template: "comprobantes/form", layout: "layouts/application"
    end

    def show
      authorize!(:update, :Comprobante)
      render template: "comprobantes/form", layout: "layouts/application"
    end

    def edit
      authorize!(:update, :Comprobante)
      @params_permit = params.present? ? {q: params.permit! } : {}
      render template: "comprobantes/form", layout: "layouts/application"
    end

    def excel_index
      respond_to do |formato|
        formato.xlsx do
          render(
            xlsx: "excel_index",
            filename: "Comprobantes del sistema - #{Date.today}.xlsx"
          )
        end
      end
    end

    def comprobante_odt
      comprobante = Comprobante.find(params[:q][:id])
      reporte = ODFReport::Report.new( Rails.root.join("app", "assets/documents/comprobante.odt")) do |odt|

      end

      send_data reporte.generate, type: "application/vnd.oasis.opendocument.text", disposition: "attachment",
                                        filename: "Comprobante.odt"
    end

    def create
      begin
        if @registro.save!
          flash[:notice] = "El registro fue guardado exitosamente"
          redirect_to action: :index
        end
      rescue StandardError => e
        flash[:error] = "Ocurrio un error al guardar los datos" if flash.now[:error].blank?
        render template: "comprobantes/form", layout: "layouts/application"
      end
    end

    def update
      begin
        if @registro.save!
          flash[:notice] = "El registro fue actualizado exitosamente"
          redirect_to action: :index
        end
      rescue StandardError => e
        flash[:error] = "Ocurrio un error al actualizar los datos" if flash.now[:error].blank?
        render template: "comprobantes/form", layout: "layouts/application"
      end
    end

    def destroy
      authorize!(:destroy, :Comprobante)
      begin
        flash[:notice] = "El registro ha sido eliminado exitosamente" if @registro.destroy
      rescue StandardError => e
        flash[:alert] = e.message
      end

      redirect_to action: :index, search: params[:q]
    end

    def obtener_pagare_socios
      pagare_usuario = Pagare.where(socio_id: params[:socio_id], cancelado: false)
      opciones = view_context.options_from_collection_for_select(pagare_usuario, :id, :numero_pagare)
      render json: { lista: opciones}, status: Rack::Utils::SYMBOL_TO_STATUS_CODE[:ok]
    end

    def obtener_informacion_cuotas
      pagare_usuario = Pagare.obtener_cuotas_pagare(params[:pagare_id])
      render json: { total_pendiente: pagare_usuario[:total_pendiente], monto_cuota: pagare_usuario[:monto_cuota], numero_cuota: pagare_usuario[:numero_cuota],
                     monto_pendiente_cuota: pagare_usuario[:monto_pendiente_cuota]}, status: Rack::Utils::SYMBOL_TO_STATUS_CODE[:ok]
    end

    def obtener_totales
      totales = FormaPago.procesar_totales(params[:pagos])
      render json: { total: totales[:total_formateado], pagos: totales[:pagos] }, status: Rack::Utils::SYMBOL_TO_STATUS_CODE[:ok]
    end

    def configurar_comprobante
      totales = FormaPago.procesar_totales(@registro.comprobante_detalle)
      @registro.usuario_id = current_usuario.id
      @registro.monto_pagado = totales[:total]
    end

    def comprobante_odt
      comprobante = Comprobante.find(params[:q][:id])
      totales = FormaPago.procesar_totales(comprobante.comprobante_detalle)
      reporte = ODFReport::Report.new( Rails.root.join("app", "assets/documents/comprobante.odt")) do |odt|
        odt.add_field :numero, comprobante.numero_comprobante
        odt.add_field :cliente, comprobante.socio.display_name
        odt.add_field :cedula, comprobante.socio.numero_cedula
        odt.add_field :direccion, comprobante.socio.direccion_domiciliar
        odt.add_field :telefono, comprobante.socio.numero_telefono
        odt.add_field :fecha, comprobante.created_at
        odt.add_field :plazo, comprobante.pagare.plazo.plazo
        odt.add_field :vendedor, comprobante.usuario.nombre
        odt.add_field :total_pagado, totales[:total_formateado]

        odt.add_field :f_0, totales[:pagos][0].try(:[], :nombre_pago)
        odt.add_field :f_1, totales[:pagos][1].try(:[], :nombre_pago)
        odt.add_field :f_2, totales[:pagos][2].try(:[], :nombre_pago)
        odt.add_field :f_3, totales[:pagos][3].try(:[], :nombre_pago)
        odt.add_field :f_4, totales[:pagos][4].try(:[], :nombre_pago)

        odt.add_field :m_0, totales[:pagos][0].try(:[], :monto_convertido)
        odt.add_field :m_1, totales[:pagos][1].try(:[], :monto_convertido)
        odt.add_field :m_2, totales[:pagos][2].try(:[], :monto_convertido)
        odt.add_field :m_3, totales[:pagos][3].try(:[], :monto_convertido)
        odt.add_field :m_4, totales[:pagos][4].try(:[], :monto_convertido)

        odt.add_field :o_0, totales[:pagos][0].try(:[], :referencia)
        odt.add_field :o_1, totales[:pagos][1].try(:[], :referencia)
        odt.add_field :o_2, totales[:pagos][2].try(:[], :referencia)
        odt.add_field :o_3, totales[:pagos][3].try(:[], :referencia)
        odt.add_field :o_4, totales[:pagos][4].try(:[], :referencia)
      end

      send_data reporte.generate, type: "application/vnd.oasis.opendocument.text", disposition: "attachment",
                                        filename: "Comprobante.odt"
    end

    private

      def nombre_recurso
        "Comprobante"
      end

      def comprobante_params
        params.require(:comprobante)
              .permit(:id, :numero_comprobante, :pagare_id, :usuario_id, :socio_id, :tipo_moneda_id,
                      :monto_pagado, :observacion,
                      comprobante_detalle_attributes: [:id, :comprobante_id, :forma_pago_id, :monto_pagado,
                                                        :referencia])
      end

      alias :params_permit :comprobante_params
end

app/views/comprobantes/_comprobante_detalle_items.html.erb
<%
    indice_fila = indice
    pago_id = pago[:pago_id]
    moneda = pago[:moneda]
    monto_pagado = pago[:monto_convertido]
    monto_convertido = pago[:monto_convertido]
    referencia = pago[:referencia]
    disabled = "disabled" if !@registro.new_record?
%>

<div id="template" class="row">
    <div class="form-group mb-2 col-lg-3">
        <select name="comprobante[comprobante_detalle_attributes][<%= indice_fila  %>][forma_pago_id]" class="form-control forma_pago_input" data-width="100%" <%= disabled %>>
            <%= options_from_collection_for_select(FormaPago.all, :id, :nombre, pago_id) %>
        </select>
    </div>

    <div class="form-group mb-2 moneda col-lg-2">
        <input class="form-control tipo_moneda_id" type="text" value ="<%= moneda %>" readonly>
    </div>

    <div class="form-group mb-2 monto col-lg-2">
        <input type="number" value="<%= monto_pagado %>" min="0" step="0.01" name="comprobante[comprobante_detalle_attributes][<%= indice_fila %>][monto_pagado]" class="form-control monto_input" type="text" <%= disabled %>>
    </div>

    <div class="form-group mb-2 monto_total col-lg-2">
        <input class="form-control monto_convertido" value="<%= monto_convertido %>" type="text" readonly>
    </div>

    <div class="form-group mb-2 concepto col-lg-2">
        <input name="comprobante[comprobante_detalle_attributes][<%= indice_fila %>][referencia]" class="form-control concepto_input" type="text" value="<% referencia %>" <%= disabled %>>
    </div>

    <% if @registro.new_record? %>
        <div class="form-group mb-2 concepto col-lg-1">
            <button type="button" class="btn btn-instagram btn-icon-only rounded-circle eliminar_fila">
                <span class="btn-inner--icon"><i class="ni ni-fat-remove"></i></span>
            </button>
        </div>
    <% end %>
</div>

app/views/comprobantes/_comprobante_formulario.html.erb
<div class="col-lg-12 col-12 mb-3">
   <div class="row">
      <div class="col-lg-12 text-right">
        <% unless @registro.new_record? %>
            <%= link_to "Comprobante", comprobante_odt_comprobantes_path(@params_permit), class: "btn btn-lg btn-danger" %>
        <% end %>
      </div>
   </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card-wrapper">
            <div class="card">
                <div class="card-header">
                    <h3 class="mb-0">Información del Comprobante</h3>
                </div>
                <div class="card-body row">
                    <%= hidden_field(:comprobante, :id, :value => @registro.id) %>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="form-control-label" for="Socio">Socio</label>
                            <%= select_tag "comprobante[socio_id]", options_from_collection_for_select(Socio.all, :id, :display_name, @registro.socio_id),
                                class: "form-control selectpicker", "data-live-search": "true", "disabled": !@registro.new_record? %>
                            <p class="text-danger"><%= @registro.errors[:socio_id].first %></p>
                        </div>
                        <div class="form-group">
                            <label class="form-control-label" for="observacion">Observación</label>
                            <%= text_field(:comprobante, :observacion, class: "form-control", id: "observacion", value: @registro.observacion, disabled: !@registro.new_record?) %>
                            <p class="text-danger"><%= @registro.errors[:observacion].first %></p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="form-control-label" for="pagare_id">Numero de Pagare</label>
                            <%= select_tag "comprobante[pagare_id]", options_from_collection_for_select(@registro.socio&.obtener_pagare_socio || [], :id, :numero_pagare, @registro.pagare_id),
                                class: "form-control selectpicker", "data-live-search": "true", "disabled": !@registro.new_record? %>
                            <p class="text-danger"><%= @registro.errors[:pagare_id].first %></p>
                        </div>
                        <div class="form-group">
                            <label class="form-control-label" for="numero">Numero Comprobante</label>
                            <%= text_field(:comprobante, :numero_comprobante, class: "form-control", id: "numero", value: @registro.obtener_numero, readonly: true) %>
                            <p class="text-danger"><%= @registro.errors[:numero_comprobante].first %></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<% if @registro.new_record? %>
  <%= render partial: 'comprobantes/informacion_cuotas' %>
<% end %>

<div class="row">
    <div class="col-lg-12">
        <div class="card-wrapper">
            <div class="card">
                <div class="card-header">
                    <h3 class="mb-0">Detalle de Pagos</h3>
                </div>
                <div id="headers" class="card-body pb-0">
                    <div class="row">
                        <div class="form-group col-lg-3">
                            <label class="form-control-label">Forma de Pago</label>
                        </div>

                        <div class="form-group moneda col-lg-2">
                            <label class="form-control-label">Moneda</label>
                        </div>

                        <div class="form-group monto col-lg-2">
                            <label class="form-control-label">Monto / Litros</label>
                        </div>

                        <div class="form-group monto_total col-lg-2">
                            <label class="form-control-label">Monto Convertido $</label>
                        </div>

                        <div class="form-group concepto col-lg-3">
                            <label class="form-control-label">Observación</label>
                        </div>
                    </div>
                </div>

                <div id="detalle_pagos" class="card-body pt-0">
                    <% totales = FormaPago.procesar_totales(@registro.comprobante_detalle) %>
                    <% totales[:pagos].each_with_index do |pago, indice| %>
                        <%= render partial: 'comprobantes/comprobante_detalle_items',
                            locals: {
                                indice: indice,
                                pago: pago
                            }
                        %>
                    <% end %>
                </div>

                <% if @registro.new_record? %>
                    <div class="row ml-4 mb-4">
                        <button id="agregar_fila" type="button" class="btn btn-twitter btn-icon-only rounded-circle">
                            <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
                        </button>
                    </div>
                <% end %>
                <h3 class="text-right mr-5 mb-4">Total Abonado: <span id="total_abonado"><%= totales[:total_formateado] %></span></h3>
            </div>
        </div>
    </div>
</div>

<%= render partial: 'comprobantes/comprobante_template' %>

app/views/comprobantes/_comprobante_template.html.erb
<div id="template" class="row invisible fila">
    <div class="form-group mb-2 col-lg-3">
        <select name="comprobante[comprobante_detalle_attributes][0][forma_pago_id]" class="form-control forma_pago_input" data-width="100%" disabled>
            <%= options_from_collection_for_select(FormaPago.all, :id, :nombre) %>
        </select>
    </div>

    <div class="form-group mb-2 moneda col-lg-2">
        <input class="form-control tipo_moneda_id" type="text" readonly>
    </div>

    <div class="form-group mb-2 monto col-lg-2">
        <input type="number" value="0" min="0" step="0.01" name="comprobante[comprobante_detalle_attributes][0][monto_pagado]" class="form-control monto_input" type="text" disabled>
    </div>

    <div class="form-group mb-2 monto_total col-lg-2">
        <input class="form-control monto_convertido" type="text" readonly>
    </div>

    <div class="form-group mb-2 concepto col-lg-2">
        <input name="comprobante[comprobante_detalle_attributes][0][referencia]" class="form-control concepto_input" type="text" disabled>
    </div>

    <div class="form-group mb-2 concepto col-lg-1">
        <button type="button" class="btn btn-instagram btn-icon-only rounded-circle eliminar_fila">
            <span class="btn-inner--icon"><i class="ni ni-fat-remove"></i></span>
        </button>
    </div>
</div>

app/views/comprobantes/_filtros.html.erb
<div class="col-lg-6 text-left">
    <button class="btn btn-lg btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="btn-inner--icon"><i class="fas fa-search"></i></span>
            <span class="btn-inner--text">Filtros</span>
    </button>

    <div class="dropdown-menu w-60">
        <%= search_form_for @coleccion, url: comprobantes_path, class: "px-4 py-3 text-center" do |formulario| %>
            <div class="form-group text-left">
                <%= label_tag(:numero_comprobante_eq, "Numero:") %>
                <%= text_field_tag "q[numero_comprobante_eq]", params[:q][:numero_comprobante_eq], class: "form-control" %>
            </div>
            <div class="form-group text-left">
                <%= label_tag(:monto_pagado_eq, "Monto Pagado:") %>
                <%= text_field_tag "q[numero_comprobante_eq]", params[:q][:numero_comprobante_eq], class: "form-control" %>
            </div>
            <%= formulario.submit class: "btn btn-primary text-center" %>
            <%= link_to "Quitar Filtros", comprobantes_path, class: "btn btn-danger text-center" %>
        <% end %>
     </div>
</div>

app/views/comprobantes/_informacion_cuotas.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="card-wrapper">
            <div class="card">
                <div class="card-header">
                    <h3 class="mb-0">Información de Cuotas</h3>
                </div>
                <div class="card-body row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="form-control-label">Total Pendiente : <span id="total_pendiente">USD 0.00</span></label>
                        </div>
                        <div class="form-group">
                            <label class="form-control-label">Numero de Cuota : <span id="numero_cuota">?</span></label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="form-control-label">Cuota: <span id="monto_cuota">USD 0.00</span></label>
                        </div>
                        <div class="form-group">
                            <label class="form-control-label">Pendiente Cuota: <span id="monto_pendiente">USD 0.00</span></label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/comprobantes/form.html.erb
<% content_for :titulo_seccion do %>
  Comprobante
<% end %>

<%= render "shared/flash", flash: flash %>
<%= javascript_include_tag "comprobante" %>
<%= render partial: "comprobantes/comprobante_formulario", layout: "layouts/formulario",
    locals: {
        registro: @registro,
        url: @url
    }
%>

app/views/comprobantes/index.html.erb
<% content_for :titulo_seccion do %>
  Comprobante
<% end %>

<div class="col-lg-12 col-12">
   <div class="row">
      <%= render "comprobantes/filtros" %>
      <div class="col-lg-6 text-right">
         <%= link_to "Descargar Excel", excel_index_comprobantes_path(@params_permit), class: "btn btn-lg btn-success" %>
         <%= link_to "Crear Recurso", new_comprobante_path, class: "btn btn-lg btn-neutral" %>
      </div>
   </div>
</div>

<div class="container-fluid mt-3">
   <div class="row">
      <div class="col pl-0 pr-0">
         <div class="card">
            <div class="card-header">
               <h3 class="mb-0">Comprobantes registrados</h3>
            </div>
            <div class="table-responsive">
               <table class="table align-items-center table-flush">
                  <thead class="thead-light">
                     <tr>
                        <th class="sort"><%= sort_link(@coleccion, :numero_comprobante, "Numero") %></th>
                        <th class="sort"><%= sort_link(@coleccion, :pagare_id, "Pagare") %></th>
                        <th class="sort"><%= sort_link(@coleccion, :usuario_id, "Usuario") %></th>
                        <th class="sort"><%= sort_link(@coleccion, :monto_pagado, "Monto Pagado") %></th>
                        <th>Socio</th>
                        <th>Mostrar</th>
                        <th>Eliminar</th>
                     </tr>
                  </thead>
                  <tbody class="list">
                    <% @registros.each do |comprobante| %>
                     <tr>
                        <td><%= comprobante.numero_comprobante %></td>
                        <td><%= comprobante.pagare.numero_pagare %></td>
                        <td><%= comprobante.usuario.nombre %></td>
                        <td><%= comprobante.monto_pagado %></td>
                        <td><%= comprobante.socio.display_name %></td>
                        <td>
                           <%= link_to edit_comprobante_path(comprobante), class: "btn btn-icon btn-primary" do %>
                              <i class="ni ni-align-left-2"></i>
                           <% end %>
                        </td>
                        <td>
                           <%= link_to comprobante_path(comprobante), class: "btn btn-icon btn-danger", method: :delete do %>
                              <i class="ni ni-scissors"></i>
                           <% end %>
                        </td>
                     </tr>
                    <% end %>
                  </tbody>
               </table>
            </div>
            <div class="card-footer py-4">
             <%= paginate @registros %>
             <%= page_entries_info @registros %>
            </div>
         </div>
      </div>
   </div>
</div>