config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: { sessions: "usuarios/sessions" }, path_prefix: "auth"

  resources :home
  resources :informacion_general
  resources :graficos

  resources :pagares do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
    get :pagare_odt, on: :collection, defaults: { :format => "odt" }
    get :calendario_pdf, on: :collection, defaults: { :format => "pdf" }
  end

  resources :comprobantes do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
    get :obtener_pagare_socios, on: :collection
    get :obtener_informacion_cuotas, on: :collection
    get :obtener_totales, on: :collection
    get :comprobante_odt, on: :collection, defaults: { :format => "odt" }
  end

  resources :socios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :cargos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :roles do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :tasa_cambios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end
  match 'tasa_cambios/bcn_webservice' => 'tasa_cambios#bcn_webservice', via: :post

  resources :empresa

  resources :bancos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :exceden_prestamos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :clientes_nuevos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :clientes_cuotas_vencidas do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :clientes_morosos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :formas_pagos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :valor_leches do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :usuarios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  match 'tasa_cambio_leche' => 'valor_leches#crear_tasa_cambio_diaria', via: :post
  match 'obtener_pagare_socios' => 'comprobantes#obtener_pagare_socios', via: :get
  match 'obtener_informacion_cuotas' => 'comprobantes#obtener_informacion_cuotas', via: :get
  match 'obtener_totales' => 'comprobantes#obtener_totales', via: :get
  root to: "home#index"
end

app/controllers/informacion_general_controller.rb
class InformacionGeneralController < ApplicationController
  before_action :authenticate_usuario!
  load_and_authorize_resource class: :InformacionGeneral

  def index
    render template: "informacion_general/index",  layout: 'layouts/application'
  end

  def show
  end

  def new
    render template: "informacion_general/form",  layout: 'layouts/application'
  end
end

app/views/informacion_general/index.html.erb
<% content_for :titulo_seccion do %>
  Información General
<% end %>
<%
   numero_registros = 5
%>
<div class="row">
   <div class="col-xl-4 col-md-6">
      <div class="card card-stats">
         <div class="card-body">
            <div class="row">
               <div class="col">
                  <h5 class="card-title text-uppercase text-muted mb-0">Pagares</h5>
                  <span class="h2 font-weight-bold mb-0"><%= Pagare.count %></span>
               </div>
               <div class="col-auto">
                  <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                     <i class="ni ni-money-coins"></i>
                  </div>
               </div>
            </div>
            <p class="mt-3 mb-0 text-sm"></p>
         </div>
      </div>
   </div>
   <div class="col-xl-4 col-md-6">
      <div class="card card-stats">
         <div class="card-body">
            <div class="row">
               <div class="col">
                  <h5 class="card-title text-uppercase text-muted mb-0">Comprobantes</h5>
                  <span class="h2 font-weight-bold mb-0"><%= Comprobante.count %></span>
               </div>
               <div class="col-auto">
                  <div class="icon icon-shape bg-gradient-green text-white rounded-circle shadow">
                     <i class="ni ni-archive-2"></i>
                  </div>
               </div>
            </div>
            <p class="mt-3 mb-0 text-sm"></p>
         </div>
      </div>
   </div>
   <div class="col-xl-4 col-md-6">
      <div class="card card-stats">
         <div class="card-body">
            <div class="row">
               <div class="col">
                  <h5 class="card-title text-uppercase text-muted mb-0">Socios</h5>
                  <span class="h2 font-weight-bold mb-0"><%= Socio.count %></span>
               </div>
               <div class="col-auto">
                  <div class="icon icon-shape bg-gradient-info text-white rounded-circle shadow">
                     <i class="ni ni-chart-bar-32"></i>
                  </div>
               </div>
            </div>
            <p class="mt-3 mb-0 text-sm">
            </p>
         </div>
      </div>
   </div>
</div>
<div class="row">
   <div class="col-xl-4">
      <div class="card">
         <div class="card-header border-0">
            <div class="row align-items-center">
               <div class="col">
                  <h5 class="mb-0">
                  Ultimos Pagares</h3>
               </div>
               <div class="col text-right">
                  <a href="<%= pagares_path %>" class="btn btn-sm btn-primary">Mirar Todos</a>
               </div>
            </div>
         </div>
         <div class="table-responsive">
            <table class="table align-items-center table-flush">
               <thead class="thead-light">
                  <tr>
                     <th scope="col">Numero</th>
                     <th scope="col">Monto Prestado</th>
                  </tr>
               </thead>
               <tbody>
                  <% Pagare.last(numero_registros).each do |pagare|%>
                     <tr>
                        <td><%= link_to pagare.numero_pagare, edit_pagare_path(pagare) %></td>
                        <td><%= "#{pagare.cantidad_solicitada} #{TipoMoneda.obtener_simbolo_moneda(TipoMoneda::CORDOBA)}" %></td>
                     </tr>
                  <% end %>
               </tbody>
            </table>
         </div>
      </div>
   </div>
   <div class="col-xl-4">
      <div class="card">
         <div class="card-header border-0">
            <div class="row align-items-center">
               <div class="col">
                  <h5 class="mb-0">
                  Ultimos Comprobantes</h3>
               </div>
               <div class="col text-right">
                  <a href="<%= comprobantes_path %>" class="btn btn-sm btn-primary">Mirar Todos</a>
               </div>
            </div>
         </div>
         <div class="table-responsive">
            <table class="table align-items-center table-flush">
               <thead class="thead-light">
                  <tr>
                     <th scope="col">Numero</th>
                     <th scope="col">Monto Abonado</th>
                  </tr>
               </thead>
               <tbody>
                  <% Comprobante.last(numero_registros).each do |comprobante|%>
                        <tr>
                           <td><%= link_to comprobante.numero_comprobante, edit_comprobante_path(comprobante) %></td>
                           <td><%= "#{comprobante.monto_pagado} #{TipoMoneda.obtener_simbolo_moneda(TipoMoneda::DOLAR)}" %></td>
                        </tr>
                  <% end %>
               </tbody>
            </table>
         </div>
      </div>
   </div>
   <div class="col-xl-4">
      <div class="card">
         <div class="card-header border-0">
            <div class="row align-items-center">
               <div class="col">
                  <h5 class="mb-0">
                  Ultimos Socios</h3>
               </div>
               <div class="col text-right">
                  <a href="<%= socios_path %>" class="btn btn-sm btn-primary">Mirar Todos</a>
               </div>
            </div>
         </div>
         <div class="table-responsive">
            <table class="table align-items-center table-flush">
               <thead class="thead-light">
                  <tr>
                     <th scope="col">Codigo de Socio</th>
                     <th scope="col">Nombre</th>
                  </tr>
               </thead>
               <tbody>
                  <% Socio.last(numero_registros).each do |socio|%>
                     <tr>
                        <td><%= link_to socio.codigo_socio, edit_socio_path(socio) %></td>
                        <td><%= socio.display_name %></td>
                     </tr>
                  <% end %>
               </tbody>
            </table>
         </div>
      </div>
   </div>
</div>