config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: { sessions: "usuarios/sessions" }, path_prefix: "auth"

  resources :home
  resources :informacion_general
  resources :graficos

  resources :pagares do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
    get :pagare_odt, on: :collection, defaults: { :format => "odt" }
    get :calendario_pdf, on: :collection, defaults: { :format => "pdf" }
  end

  resources :comprobantes do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
    get :obtener_pagare_socios, on: :collection
    get :obtener_informacion_cuotas, on: :collection
    get :obtener_totales, on: :collection
    get :comprobante_odt, on: :collection, defaults: { :format => "odt" }
  end

  resources :socios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :cargos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :roles do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :tasa_cambios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end
  match 'tasa_cambios/bcn_webservice' => 'tasa_cambios#bcn_webservice', via: :post

  resources :empresa

  resources :bancos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :exceden_prestamos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :clientes_nuevos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :clientes_cuotas_vencidas do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :clientes_morosos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :formas_pagos do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :valor_leches do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :usuarios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  match 'tasa_cambio_leche' => 'valor_leches#crear_tasa_cambio_diaria', via: :post
  match 'obtener_pagare_socios' => 'comprobantes#obtener_pagare_socios', via: :get
  match 'obtener_informacion_cuotas' => 'comprobantes#obtener_informacion_cuotas', via: :get
  match 'obtener_totales' => 'comprobantes#obtener_totales', via: :get
  root to: "home#index"
end

app/controllers/valor_leches_controller.rb
class ValorLechesController < ApplicationController
  include Controleable
  before_action :authenticate_usuario!
  before_action :coleccion_inicial, only: %i[index excel_index]

  def coleccion_inicial
    params[:q] ||= {}
    @coleccion = ValorLeche.ransack(params[:q])
    @coleccion.sorts = ["fecha asc"] if @coleccion.sorts.empty?
    respond_to do |formato|
      formato.html do
        @registros = @coleccion.result.page(params[:page])
      end
      formato.xlsx do
        @registros = @coleccion.result
      end
    end
  end

  def index
    authorize!(:read, :ValorLeche)
    @params_permit = params[:q].present? ? {q: params[:q] .permit! } : {}
    render template: "valor_leches/index",  layout: "layouts/application"
  end

  def new
    authorize!(:create, :ValorLeche)
    render template: "valor_leches/form", layout: "layouts/application"
  end

  def show
    authorize!(:update, :ValorLeche)
    render template: "valor_leches/form", layout: "layouts/application"
  end

  def edit
    authorize!(:update, :ValorLeche)
    render template: "valor_leches/form", layout: "layouts/application"
  end

  def excel_index
    respond_to do |formato|
      formato.xlsx do
        render(
          xlsx: "excel_index",
          filename: "Valores de la leche del sistema - #{Date.today}.xlsx"
        )
      end
    end
  end

  def create
    begin
      if @registro.save!
        flash[:notice] = "El registro fue guardado exitosamente"
        redirect_to action: :index
      end
    rescue StandardError => e
      flash[:error] = "Ocurrio un error al guardar los datos" if flash.now[:error].blank?
      render template: "valor_leches/form", layout: "layouts/application"
    end
  end

  def update
    begin
      if @registro.save!
        flash[:notice] = "El registro fue actualizado exitosamente"
        redirect_to action: :index
      end
    rescue StandardError => e
      flash[:error] = "Ocurrio un error al actualizar los datos" if flash.now[:error].blank?
      render template: "valor_leches/form", layout: "layouts/application"
    end
  end

  def destroy
    authorize!(:destroy, :ValorLeche)
    begin
      flash[:notice] = "El registro ha sido eliminado exitosamente" if @registro.destroy
    rescue StandardError => e
      flash[:error] = e.message
    end

    redirect_to action: :index, search: params[:q]
  end

  def crear_tasa_cambio_diaria
    begin
      ValorLeche.new(tasa_cambio: params[:tasa_cambio], fecha: Date.today).save!
      render json: { mensaje: "Se creo el valor para el dia de hoy exitosamente."}, status: Rack::Utils::SYMBOL_TO_STATUS_CODE[:ok]
    rescue StandardError => e
      render json: { mensaje: "Hubo un error al comunicarse con el servicio web del BCN."}, status: Rack::Utils::SYMBOL_TO_STATUS_CODE[:internal_server_error]
    end
  end

  private

    def nombre_recurso
      "ValorLeche"
    end

    def valorleche_params
      params.require(:valor_leches).permit(:id, :tasa_cambio, :fecha)
    end

    alias :params_permit :valorleche_params
end

app/views/valor_leches/_filtros.html.erb
<div class="col-lg-6 text-left">
    <div class="btn-group">
        <button class="btn btn-lg btn-default dropdown-toggle" type="button" id="filtros" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="btn-inner--icon"><i class="fas fa-search"></i></span>
            <span class="btn-inner--text">Filtros</span>
        </button>

        <div class="dropdown-menu scopes_heigth">
            <%= search_form_for @coleccion, url: valor_leches_path, class: "px-4 py-3 text-center" do |formulario| %>
                <div class="form-group text-left">
                    <%= label_tag(:fecha_eq, "Fecha:") %>
                    <%= date_field_tag "q[fecha_eq]", params[:q][:fecha_eq], class: "form-control" %>
                </div>
                <div class="form-group text-left">
                    <%= label_tag(:tasa_cambio_eq, "Tasa de Cambio:") %>
                    <%= text_field_tag "q[tasa_cambio_eq]", params[:q][:tasa_cambio_eq], class: "form-control" %>
                </div>
                <div class="form-group text-left">
                    <%= formulario.submit class: "btn btn-primary text-center" %>
                    <%= link_to "Quitar Filtros", valor_leches_path, class: "btn btn-danger text-center" %>
                </div>
            <% end %>
        </div>
    </div>

    <div class="btn-group">
        <button class="btn btn-lg btn-danger dropdown-toggle" type="button" id="scopes" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="btn-inner--icon"><i class="ni ni-tag"></i></span>
            <span class="btn-inner--text">Filtros Especificos</span>
        </button>

        <div class="dropdown-menu scopes_heigth" aria-labelledby="scopes">
            <a class="dropdown-item" href="valor_leches?q%5Bmes_eq%5D=true">Mes</a>
        </div>
    </div>
</div>

app/views/valor_leches/_valores_leches_formulario.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="card-wrapper">
            <div class="card">
                <div class="card-header">
                    <h3 class="mb-0">Información del Valor de la Leche</h3>
                </div>
                <div class="card-body">
                    <%= hidden_field(:valor_leches, :id, :value => @registro.id) %>
                    <div class="form-group">
                        <label class="form-control-label" for="nombre">Fecha</label>
                        <%= date_field(:valor_leches, :fecha, class: "form-control", id: "fecha", value: @registro.fecha) %>
                        <p class="text-danger"><%= @registro.errors[:fecha].first %></p>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="nombre">Tasa de Cambio</label>
                        <%= text_field(:valor_leches, :tasa_cambio, class: "form-control", id: "tasa_cambio", value: @registro.tasa_cambio) %>
                        <p class="text-danger"><%= @registro.errors[:tasa_cambio].first %></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/valor_leches/form.html.erb
<% content_for :titulo_seccion do %>
  Valor De La Leche
<% end %>

<%= render "shared/flash", flash: flash %>
<%= render partial: 'valor_leches/valores_leches_formulario', layout: "layouts/formulario",
    locals: {
        registro: @registro,
        url: @url
    }
%>

app/views/valor_leches/index.html.erb
<% content_for :titulo_seccion do %>
  Valor De La Leche
<% end %>

<div class="col-lg-12 col-12">
   <div class="row">
      <%= render 'valor_leches/filtros' %>
      <div class="col-lg-6 text-right">
         <%= link_to "Descargar Excel", excel_index_valor_leches_path(@params_permit), class: "btn btn-lg btn-success" %>
         <%= link_to "Crear Recurso", new_valor_lech_path, class: "btn btn-lg btn-neutral" %>
      </div>
   </div>
</div>

<div class="container-fluid mt-3">
   <div class="row">
      <div class="col pl-0 pr-0">
         <div class="card">
            <div class="card-header">
               <h3 class="mb-0">Valores de la leche registrados</h3>
            </div>
            <div class="table-responsive">
               <table class="table align-items-center table-flush">
                  <thead class="thead-light">
                     <tr>
                        <th class="sort"><%= sort_link(@coleccion, :fecha, "Fecha") %></th>
                        <th class="sort"><%= sort_link(@coleccion, :nombre, "Tasa de Cambio") %></th>
                        <th>Actualizar</th>
                        <th>Eliminar</th>
                     </tr>
                  </thead>
                  <tbody class="list">
                    <% @registros.each do |valor_leches| %>
                     <tr>
                        <td><%= valor_leches.fecha.strftime("%d-%m-%Y") %></td>
                        <td><%= [valor_leches.tasa_cambio, TipoMoneda.obtener_simbolo_moneda(TipoMoneda::CORDOBA)].join(" ") %></td>
                        <td>
                           <%= link_to edit_valor_lech_path(valor_leches), class: "btn btn-icon btn-primary" do %>
                              <i class="ni ni-align-left-2"></i>
                           <% end %>
                        </td>
                        <td>
                           <%= link_to valor_lech_path(valor_leches), class: "btn btn-icon btn-danger", method: :delete do %>
                              <i class="ni ni-scissors"></i>
                           <% end %>
                        </td>
                     </tr>
                    <% end %>
                  </tbody>
               </table>
            </div>
            <div class="card-footer py-4">
             <%= paginate @registros %>
             <%= page_entries_info @registros %>
            </div>
         </div>
      </div>
   </div>
</div>